updated workflow

diff --git a/.github/workflows/playback-deploy.yml b/.github/workflows/playback-deploy.yml
--- a/.github/workflows/playback-deploy.yml
+++ b/.github/workflows/playback-deploy.yml
@@ -19,6 +19,7 @@ jobs:
         with:
           role-to-assume: ${{ secrets.OIDC_ARN}} #oidc
           aws-region: ap-south-1
+
       - name: install ssh_key_pair
         run: ssh-keygen -t rsa -N "" -f "ec2_login_key"
 
@@ -28,7 +29,17 @@ jobs:
           terraform init
           terraform fmt
         continue-on-error: true
-      
+
+      - name: check code validation
+        id: validation
+        run: terraform validate
+
+      - name: check validation condition
+        if: steps.validation.outcome == 'failure'
+        run: |
+          echo "terraform configurations are invalid, skipping further steps.."
+          exit 1
+
       - name: Setup TFLint
         uses: terraform-linters/setup-tflint@v4
         with:
@@ -40,13 +51,13 @@ jobs:
       - name: Init TFLint
         run: tflint --init
         env:
-        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
           GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
 
       - name: Run TFLint
         id: lint
         run: tflint -f compact
-        continue-on-error: true
+        # continue-on-error: true
+
       - name: Retry TFLint
         if: steps.lint.outcome == 'failure'
         run: |
@@ -54,9 +65,9 @@ jobs:
           exit 1
         continue-on-error: true
 
-      - run: echo ${{ steps.lint.outcome.stdout }}
-      - run: echo ${{ steps.lint.outcome.stderr }}
-      - run: echo ${{ steps.lint.outcome.exitcode }}
+      # - run: echo ${{ steps.lint.outcome.stdout }}
+      # - run: echo ${{ steps.lint.outcome.stderr }}
+      # - run: echo ${{ steps.lint.outcome.exitcode }}
 
       # - name: plan_apply
       #   id: plan
@@ -68,6 +79,7 @@ jobs:
       #   run: |
       #     echo "retrying plan.."
       #     terraform plan -out myplan || terraform plan -out myplan
+
       # - name: apply_plan
       #   id: apply
       #   run: terraform apply myplan
