updated terraform configuration files and workflows

diff --git a/.github/workflows/playback-deploy.yml b/.github/workflows/playback-deploy.yml
--- a/.github/workflows/playback-deploy.yml
+++ b/.github/workflows/playback-deploy.yml
@@ -36,7 +36,7 @@ jobs:
         run: ssh-keygen -t rsa -N "" -f "ec2_login_key"
 
       - name: initialize & format
-        id: init
+        id: init #initialize terraform with or without enabling logging based on inputs
         run: |
           export TF_LOG=${{ inputs.logging }}
           terraform init
@@ -79,35 +79,31 @@ jobs:
           exit 1
         continue-on-error: true
 
-      # - run: echo ${{ steps.lint.outcome.stdout }}
-      # - run: echo ${{ steps.lint.outcome.stderr }}
-      # - run: echo ${{ steps.lint.outcome.exitcode }}
+      - name: plan_apply
+        id: plan
+        run: terraform plan -out myplan
+        continue-on-error: true
 
-      # - name: plan_apply
-      #   id: plan
-      #   run: terraform plan -out myplan
-      #   continue-on-error: true
+      - name: retry_plan #(run on failure)
+        if: steps.plan.outcome == 'failure'
+        run: |
+          echo "retrying plan.."
+          terraform plan -out myplan || terraform plan -out myplan
 
-      # - name: retry_plan #(run on failure)
-      #   if: steps.plan.outcome == 'failure'
-      #   run: |
-      #     echo "retrying plan.."
-      #     terraform plan -out myplan || terraform plan -out myplan
+      - name: apply_plan
+        id: apply
+        run: terraform apply myplan
+        continue-on-error: true
 
-      # - name: apply_plan
-      #   id: apply
-      #   run: terraform apply myplan
-      #   continue-on-error: true
-
-      # - name: Post-Deployment Outputs
-      #   if: always()
-      #   run: terraform output
+      - name: Post-Deployment Outputs
+        if: always()
+        run: terraform output
         
-      # - name: Failure Notification
-      #   if: failure()
-      #   run: |
-      #     echo "Terraform provisioning Failed!"
-      #     exit 1
+      - name: Failure Notification
+        if: failure()
+        run: |
+          echo "Terraform provisioning Failed!"
+          exit 1
 
 
  
