updated lint conditions

diff --git a/.github/workflows/playback-deploy.yml b/.github/workflows/playback-deploy.yml
--- a/.github/workflows/playback-deploy.yml
+++ b/.github/workflows/playback-deploy.yml
@@ -22,7 +22,7 @@ jobs:
       - name: install ssh_key_pair
         run: ssh-keygen -t rsa -N "" -f "ec2_login_key"
 
-      - name: initialize&format
+      - name: initialize & format
         id: init
         run: |
           terraform init
@@ -52,31 +52,35 @@ jobs:
         run: |
           echo "error with terraform configurations"
           exit 1
-          
-      - name: plan_apply
-        id: plan
-        run: terraform plan -out myplan
-        continue-on-error: true
 
-      - name: retry_plan #(run on failure)
-        if: steps.plan.outcome == 'failure'
-        run: |
-          echo "retrying plan.."
-          terraform plan -out myplan || terraform plan -out myplan
-      - name: apply_plan
-        id: apply
-        run: terraform apply myplan
-        continue-on-error: true
+      - run: echo ${{ steps.lint.outputs.stdout }}
+      - run: echo ${{ steps.lint.outputs.stderr }}
+      - run: echo ${{ steps.lint.outputs.exitcode }}
 
-      - name: Post-Deployment Outputs
-        if: always()
-        run: terraform output
+      # - name: plan_apply
+      #   id: plan
+      #   run: terraform plan -out myplan
+      #   continue-on-error: true
+
+      # - name: retry_plan #(run on failure)
+      #   if: steps.plan.outcome == 'failure'
+      #   run: |
+      #     echo "retrying plan.."
+      #     terraform plan -out myplan || terraform plan -out myplan
+      # - name: apply_plan
+      #   id: apply
+      #   run: terraform apply myplan
+      #   continue-on-error: true
+
+      # - name: Post-Deployment Outputs
+      #   if: always()
+      #   run: terraform output
         
-      - name: Failure Notification
-        if: failure()
-        run: |
-          echo "Terraform provisioning Failed!"
-          exit 1
+      # - name: Failure Notification
+      #   if: failure()
+      #   run: |
+      #     echo "Terraform provisioning Failed!"
+      #     exit 1
 
 
  
